version: "3.9"
name: "phoebe"
services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_volume: