PRONOUNS = [
    "he/him",
    "she/her",
    "they/them",
    "it/its",
    "xe/xem",
    "ze/zir",
    "other",
]

SEXUAL_ORIENTATIONS = [
    "asexual",
    "aromantic",
    "bisexual",
    "demisexual",
    "gay",
    "heterosexual",
    "lesbian",
    "pansexual",
    "queer",
    "questioning",
    "other",
]

GENDERS = [
    "male",
    "female",
    "non-binary",
    "agender",
    "altersex",
    "androgyne",
    "bigender",
    "cisgender",
    "demiboy",
    "demigirl",
    "deminonbinary",
    "genderfluid",
    "genderqueer",
    "intersex",
    "pangender",
    "masculine",
    "feminine",
    "transgender male",
    "transgender female",
    "other",
]
